### ISSUE TITLE
Allow dflydev/fig-cookies v3.0

### ISSUE THREAD

**Issue by arokettu** [mezzio/mezzio-session-ext#19]
See https://github.com/mezzio/mezzio-session/issues/17

Opening an issue here too because `dflydev/fig-cookies` is a direct dependency here too

**Comment by pine3ree** [comment]
Hello @arokettu, (pinging @weierophinney )
in theory this package is now only indireclty dependent on dflydev/fig-cookies via the mezzio/session persistence-traits.
Common persistence code was moved to mezzio/session in order to avoid duplication in persistence implementations.
I forgot to move the dependency to "require-dev" in this repo.
kind regards!
